package task

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	pan "github.com/ctwj/urldb/common"
	"github.com/ctwj/urldb/db/entity"
	"github.com/ctwj/urldb/db/repo"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// AuthorizedTransferProcessor executes an authorized same-provider transfer and
// persists the share generated by the service-controlled account. It deliberately
// does not attempt cross-provider copying or any permission/captcha workaround.
type AuthorizedTransferProcessor struct {
	db      *gorm.DB
	repoMgr *repo.RepositoryManager
}

func NewAuthorizedTransferProcessor(db *gorm.DB, repoMgr *repo.RepositoryManager) *AuthorizedTransferProcessor {
	return &AuthorizedTransferProcessor{db: db, repoMgr: repoMgr}
}

func (p *AuthorizedTransferProcessor) GetTaskType() string {
	return string(entity.TaskTypeAuthorizedTransfer)
}

func (p *AuthorizedTransferProcessor) Process(ctx context.Context, taskID uint, item *entity.TaskItem) error {
	if err := ctx.Err(); err != nil {
		return err
	}

	var input struct {
		ResourceID uint   `json:"resource_id"`
		PanID      uint   `json:"pan_id"`
		CkID       uint   `json:"ck_id"`
		Channel    string `json:"channel"`
	}
	if err := json.Unmarshal([]byte(item.InputData), &input); err != nil {
		return fmt.Errorf("invalid authorized transfer input: %w", err)
	}
	if input.ResourceID == 0 || input.PanID == 0 || input.CkID == 0 {
		return errors.New("authorized transfer input is incomplete")
	}

	var resource entity.Resource
	if err := p.db.First(&resource, input.ResourceID).Error; err != nil {
		return fmt.Errorf("load resource: %w", err)
	}
	if resource.PanID == nil || *resource.PanID != input.PanID {
		return errors.New("cross-provider transfer is not enabled; resource and target platform must match")
	}

	var authorization entity.ResourceAuthorization
	if err := p.db.Where("resource_id = ? AND status = ?", input.ResourceID, "active").First(&authorization).Error; err != nil {
		return errors.New("active resource authorization is required before execution")
	}
	if authorization.RetentionUntil != nil && !authorization.RetentionUntil.After(time.Now()) {
		return errors.New("resource authorization has expired")
	}

	var account entity.Cks
	if err := p.db.Where("id = ? AND pan_id = ? AND is_valid = ?", input.CkID, input.PanID, true).First(&account).Error; err != nil {
		return errors.New("target account is invalid or belongs to another platform")
	}

	var existing entity.OwnedShare
	err := p.db.Where("resource_id = ? AND pan_id = ? AND ck_id = ? AND status = ?", input.ResourceID, input.PanID, input.CkID, "active").
		Where("expires_at IS NULL OR expires_at > ?", time.Now()).First(&existing).Error
	if err == nil {
		return p.setOutput(item, existing, true)
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		return fmt.Errorf("check existing owned share: %w", err)
	}

	shareID, serviceType := pan.ExtractShareId(resource.URL)
	if shareID == "" || serviceType == pan.NotFound {
		return errors.New("resource URL is not a supported provider share link")
	}
	providerPolicy, err := pan.AuthorizedTransferProviderPolicyFor(serviceType)
	if err != nil {
		return fmt.Errorf("authorized transfer is blocked by provider compliance policy: %w", err)
	}
	service, err := pan.NewPanFactory().CreatePanService(resource.URL, &pan.PanConfig{URL: resource.URL, Cookie: account.Ck})
	if err != nil {
		return fmt.Errorf("create provider service: %w", err)
	}
	service.SetCKSRepository(p.repoMgr.CksRepository, account)
	result, err := service.Transfer(shareID)
	if err != nil {
		return fmt.Errorf("provider transfer failed: %w", err)
	}
	if result == nil || !result.Success || result.ShareURL == "" {
		message := "provider did not return a share URL"
		if result != nil && result.Message != "" {
			message = result.Message
		}
		return fmt.Errorf("provider transfer failed: %s", message)
	}

	providerExpiry := time.Now().AddDate(0, 0, providerPolicy.MaxShareRetentionInDays)
	if authorization.RetentionUntil != nil && authorization.RetentionUntil.Before(providerExpiry) {
		providerExpiry = *authorization.RetentionUntil
	}
	owned := entity.OwnedShare{ResourceID: input.ResourceID, PanID: input.PanID, CkID: input.CkID, URL: result.ShareURL, Fid: result.Fid, Status: "active", Channel: input.Channel, ExpiresAt: &providerExpiry}
	if owned.Channel == "" {
		owned.Channel = "system"
	}
	if err := p.db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "resource_id"}, {Name: "pan_id"}, {Name: "ck_id"}},
		DoUpdates: clause.AssignmentColumns([]string{"url", "fid", "status", "channel", "expires_at", "last_checked_at", "last_check_status", "last_check_method", "last_check_fail_reason", "deleted_at", "updated_at"}),
	}).Create(&owned).Error; err != nil {
		return fmt.Errorf("persist owned share: %w", err)
	}
	if owned.ID == 0 {
		if err := p.db.Where("resource_id = ? AND pan_id = ? AND ck_id = ?", input.ResourceID, input.PanID, input.CkID).First(&owned).Error; err != nil {
			return fmt.Errorf("load persisted owned share: %w", err)
		}
	}
	return p.setOutput(item, owned, false)
}

func (p *AuthorizedTransferProcessor) setOutput(item *entity.TaskItem, owned entity.OwnedShare, reused bool) error {
	output, err := json.Marshal(map[string]interface{}{"owned_share_id": owned.ID, "share_url": owned.URL, "fid": owned.Fid, "reused": reused})
	if err != nil {
		return err
	}
	item.OutputData = string(output)
	return nil
}
